In [3]:
import numpy as np

In [5]:
arr = np.arange(0,11)

In [7]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
arr[8]

8

In [11]:
arr[1:5]

array([1, 2, 3, 4])

In [13]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
xz