In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

8

In [5]:
arr[3:4]

array([3])

In [6]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [7]:
arr[0:5] = [100]

In [8]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [9]:
arr = np.arange(0,11)

In [10]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
slice_of_arr = arr[0:6]

In [12]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [13]:
slice_of_arr[:] = 99

In [14]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [15]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [18]:
arr_2D = np.array([[5,10,15],[20,25,30],[30,35,40]])

In [19]:
arr_2D

array([[ 5, 10, 15],
       [20, 25, 30],
       [30, 35, 40]])

In [21]:
arr_2D[1][1]

25

In [22]:
arr_2D[2][2]

40

In [23]:
arr_2D[0:1][0:1]

array([[ 5, 10, 15]])

In [24]:
arr_2D[:2][:1]

array([[ 5, 10, 15]])

In [25]:
arr_2D[:2,1:]

array([[10, 15],
       [25, 30]])

In [26]:
arr_2D[:1,1:]

array([[10, 15]])

In [27]:
arr_2D[:2:]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [28]:
arr_2D[2:]

array([[30, 35, 40]])

In [29]:
arr_2D[1:]

array([[20, 25, 30],
       [30, 35, 40]])

In [30]:
arr_new_two = np.arange(1,11)

In [31]:
arr_new_two

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
arr_bool_two = arr_new_two > 5

In [33]:
arr_bool_two

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [35]:
arr_new_two[arr_bool_two]

array([ 6,  7,  8,  9, 10])

In [36]:
arr[arr>5]

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [37]:
arr_new_two[arr_new_two > 5]

array([ 6,  7,  8,  9, 10])

In [38]:
arr_new_2d = np.arange(50).reshape(5,10)

In [39]:
arr_new_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [41]:
arr_new_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [42]:
arr_new_2d[1:3]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [44]:
arr_new_2d[2:4,4:6]

array([[24, 25],
       [34, 35]])

In [45]:
arr_new_2d[3:4,8:]

array([[38, 39]])

In [46]:
arr_new_2d[3:,8:]

array([[38, 39],
       [48, 49]])