In [10]:
my_list = [1,2,3]

In [9]:
import numpy as np

In [12]:
arr = np.array(my_list)

In [13]:
arr

array([1, 2, 3])

In [14]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [15]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [19]:
np.zeros(3)

array([0., 0., 0.])

In [20]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [23]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [24]:
np.random.rand(5)

array([0.06731007, 0.64056659, 0.14629845, 0.4976719 , 0.13673843])

In [25]:
np.random.rand(5,5)

array([[0.07527061, 0.5976174 , 0.43431753, 0.14299783, 0.5924104 ],
       [0.48682036, 0.60677416, 0.27752946, 0.80584878, 0.92277081],
       [0.94139066, 0.42695595, 0.73120553, 0.4537028 , 0.38439344],
       [0.03143535, 0.80837809, 0.59020849, 0.89507883, 0.10731102],
       [0.64510009, 0.12167299, 0.04677491, 0.30410808, 0.85931665]])

In [26]:
np.random.randn(2)

array([-0.47406479, -0.5063454 ])

In [27]:
np.random.randn(4,4)

array([[ 1.09102921,  0.33307239,  0.10114185,  2.74628491],
       [-2.02057854, -1.25564037,  0.82297323, -0.09288049],
       [-0.22082834, -1.44172679, -0.14062209,  0.20534543],
       [ 0.6282893 , -0.39153148, -0.98762892, -0.31412676]])

In [28]:
np.random.randint(1,100)

54

In [29]:
arr = np.arange(25)

In [30]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [31]:
ranarr = np.random.randint(0,50,100)

In [32]:
ranarr

array([ 5,  8, 18,  0, 37,  7, 27,  4, 22,  4, 34, 14, 18, 18, 40, 15, 12,
       48, 13, 41, 21, 41,  8, 23,  0, 42,  4, 30, 12, 12,  5,  1, 35, 38,
        8, 16,  9, 27, 36, 46, 17,  5,  7, 42, 45, 29, 23, 42,  1, 32,  8,
        9, 41, 17, 27,  5, 47, 20, 38, 13, 17,  0,  7,  9, 31,  0, 23, 44,
       29,  9, 21, 33,  6,  3, 37, 29,  1,  1,  4, 44, 20, 37, 23, 38, 29,
       42, 35, 16, 44, 26, 29,  4, 38,  2, 46, 21,  1, 41, 35, 45])

In [33]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [34]:
ranarr

array([ 5,  8, 18,  0, 37,  7, 27,  4, 22,  4, 34, 14, 18, 18, 40, 15, 12,
       48, 13, 41, 21, 41,  8, 23,  0, 42,  4, 30, 12, 12,  5,  1, 35, 38,
        8, 16,  9, 27, 36, 46, 17,  5,  7, 42, 45, 29, 23, 42,  1, 32,  8,
        9, 41, 17, 27,  5, 47, 20, 38, 13, 17,  0,  7,  9, 31,  0, 23, 44,
       29,  9, 21, 33,  6,  3, 37, 29,  1,  1,  4, 44, 20, 37, 23, 38, 29,
       42, 35, 16, 44, 26, 29,  4, 38,  2, 46, 21,  1, 41, 35, 45])

In [35]:
ranarr.max()

48

In [36]:
ranaarr.min()

NameError: name 'ranaarr' is not defined

In [37]:
ranarr.min()

0

In [38]:
ranarr.argmax()

17

In [39]:
arr.shape()

TypeError: 'tuple' object is not callable

In [40]:
arr.shape

(25,)

In [41]:
arr = arr.reshape(5,5)

In [42]:
arr.shape

(5, 5)

In [43]:
arr.dtype

dtype('int32')

In [44]:
from numpy.random import randint

In [45]:
randint(2,10)

5